# Generated by Django 5.1.1 on 2024-12-07 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
