# Generated by Django 5.1.1 on 2024-11-16 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tax_data',
            field=models.JSONField(blank=True, help_text="Data format: {'tax_type':{'tax_percentage':'tax_amount'}}", null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_tax',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
