# Generated by Django 5.1.1 on 2024-11-16 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_foodorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodorder',
            name='reservation_expiration',
        ),
        migrations.RemoveField(
            model_name='foodorder',
            name='return_amount',
        ),
    ]
